version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 7.0
    commands:
      - echo "Installing dependencies..."
      - dotnet restore
  build:
    commands:
      - echo "Building .NET Core application..."
      - dotnet build --configuration Release
  post_build:
    commands:
      - echo "Build completed successfully!"
artifacts:
  files:
    - '**/*.dll'
    - '**/*.exe'
