version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 6.0
    commands:
      - echo "Using .NET 6.0 instead of 7.0..."
  build:
    commands:
      - dotnet build --configuration Release
artifacts:
  files:
    - '**/*.dll'
    - '**/*.exe'

